### ISSUE TITLE
Automatisation

### ISSUE THREAD

**Issue by ghosotte** [MisterCyp/RuFy#6]
Bonjour,
est-ce que tu as prévu dans le futur,
- de télécharger auto. selon un critère ?
- d'être compatible avec d'autres trackers francais ?
  :)

Cordialement,

**Comment by MisterCyp** [comment]
Bonjour,

> est-ce que tu as prévu dans le futur,
> de télécharger auto. selon un critère ?

Pas dans un futur proche car d'autres applications le font déjà très bien.

> est-ce que tu as prévu dans le futur,
> d'être compatible avec d'autres trackers francais ? :)

Oui mais, à vrai dire je n'utilise que T411 comme tracker francais. En as-tu d'autres à proposer ? 

Merci pour ton intérêt pour l'application.
