### ISSUE TITLE
[FEATURE] Provide a config file for apache

### ISSUE THREAD

**Issue by shyne99** [MisterCyp/RuFy#7]
Bonjour, 

Je poste ici, au cas ou d'autre aurais déja cette information. 

J'avais commencer à travailler sur un projet du même type en python, plus simpliste, et qui permettai de lancer directement la lecture d'un torrent sur vlc (en utilisant torrent-stream).
C'était déja du python à l'époque, et je pense que je pourrais essayer d'ajouter cette feature sur RuFy que je trouve très développer.

Par contre, mon serveur, comme beaucoup d'autre je pense, utilise Apache, car je trouve nginx tres complexe. 

Pourriez-vous fournir un Vhost Apache pour Rufy, sachant que sa config est assez particulière, et pas à la portée de tous. 

Merci.

**Comment by MisterCyp** [comment]
Bonjour,

Je ne connais pas trop ton projet mais ça peut être intéressant :)
Alors par contre je ne connais pas Apache mais je peux te dire les redirections à effectuer : 
- redirection de l'URI /rufy vers l'adresse : 127.0.0.1:8000 (reverse proxy)
- redirection de l'URI /rufy/static vers  /var/www/RuFy/static/ (alias) si tu as suivis l'installation par défaut

N'hésites pas si tu as des questions

EDIT : regarde ici : https://mondedie.fr/viewtopic.php?id=8018&p=3 quelqu'un avait essayé de faire tourner rufy sur Apache mais je ne sais pas s'il a réussi finalement...

**Comment by MisterCyp** [comment]
Problème résolu : config apache ici : https://github.com/MisterCyp/RuFy/blob/master/config/rufy-apache.conf
